language: c

env:
  matrix:
    - nhr_env_matrix=default
    - nhr_env_matrix=no_get CMAKE_ARGS="-DNHR_OPT_NO_GET:BOOL=ON"
    - nhr_env_matrix=no_post CMAKE_ARGS="-DNHR_OPT_NO_POST:BOOL=ON"
    - nhr_env_matrix=no_get_post CMAKE_ARGS="-DNHR_OPT_NO_GET:BOOL=ON -DNHR_OPT_NO_POST:BOOL=ON"
    - nhr_env_matrix=no_chunked CMAKE_ARGS="-DNHR_OPT_NO_CHUNKED:BOOL=ON"
    - nhr_env_matrix=no_gzip CMAKE_ARGS=-DNHR_OPT_NO_GZIP:BOOL=ON"

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=~/libnhr-install-dir -DCMAKE_BUILD_TYPE=Release $CMAKE_ARGS ..
  - cd ..

script:
  - cd build
  - make
  - make test
  - make install

branches:
  only:
    - master
    - dev
